version: "3"

services:
  books-service:
    container_name: books-service
    image: smalldog124/book-crawler:0.3
    depends_on: 
        - books-db
    ports:
    - "3030:3030"
  books-db:
    container_name: books-db
    image: postgres:11.1-alpine
    restart: always
    environment:
      POSTGRES_PASSWORD: example
      POSTGRES_USER: smalldoc
      POSTGRES_DB: books_collection_th
    ports:
      - 5432:5432
    volumes:
      - ./initdb.sql:/docker-entrypoint-initdb.d/initdb.sql
  book-ui:
    container_name: book-ui
    image: smalldog124/book-ui:0.3
    depends_on: 
      - books-service
    ports: 
    - "8000:80"
