version: "3"

services:
  books-service:
    container_name: books-service
    image: smalldog124/book-crawler:0.3
    depends_on: 
        - books-db
    ports:
    - "3030:3030"
  books-db:
    container_name: books-db
    image: mongo:3.6
    ports: 
    - "27017:27017"
  book-ui:
    container_name: book-ui
    image: smalldog124/book-ui:0.3
    depends_on: 
      - books-service
    ports: 
    - "8000:80"
